### ISSUE TITLE
Possibility to import Blueprints without updating the mod itself

### ISSUE THREAD

**Issue by Dominik-O22** [Choumiko/Foreman#3]
Is it possible to load the blueprints from the script output folder instead of from the mod folder itself?

**Comment by Choumiko** [comment]
Sadly not, mods can only read/require a file inside their own mod folder.
As an alternative to copy/pasting the file in the mod folder/zip i probably could change the importing (via "+" button) to accept multiple blueprints in one go.
The current workaround is bound to fail in multiplayer sooner or later due to md5 checks of the mod

**Comment by Dominik-O22** [comment]
yeah and with no way to do anything about that really sucks
